#!/bin/bash
# Copyright (c) 2022 Theo Brown

__namestring="\
###############
# conda-setup #
###############
Miniconda3 install & configuration script
Copyright (c) 2022 Theo Brown (MIT License)
"

__docstring="\
$__namestring
Usage:
  conda-setup [-f | --force] [-g | --global] [-h | --help] [-q | --quiet] [-s | --silent]
              [-d INSTALL_DIRECTORY | --install-dir INSTALL_DIRECTORY]
              [-p PYTHON_VERSION | --python-version PYTHON_VERSION]
              [-B | --hide-base] [--no-auto-activate] [--no-init]

Installation options:
  -f | --force              If \$INSTALL_DIRECTORY/miniconda exists, overwrite it
  -g | --global             Install conda system-wide, equivalent to 'conda-setup -d /opt'
  -h | --help               Print this help
  -q | --quiet              Non-interactive mode - run without prompt and use defaults for any options not set with flags
  -s | --silent             Silent mode - suppress all output, and use defaults for any options not set with flags

  -d INSTALL_DIRECTORY | --install-dir INSTALL_DIRECTORY
     Install conda to the given location; it will be found at \$INSTALL_DIRECTORY/miniconda
  -p PYTHON_VERSION | --python PYTHON_VERSION
     Install the specified version of Python (default: Miniconda's default Python version)

Configuration options:
  -B | --hide-base          Hide '(base)' in shell prompt (for non-base environments it will still appear)
  --no-auto-activate        Disable automatic activation of base environment
  --no-init                 Don't run 'conda init' after installation
"

# Exit when any command fails
set -e

# Set defaults
MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
FORCE_INSTALL=false
QUIET_MODE=false
INSTALL_DIRECTORY="$HOME/.miniconda3"
PYTHON_VERSION=""
DISABLE_AUTO_ACTIVATE=false
RUN_CONDA_INIT=true
HIDE_BASE=false

# Parse arguments by iterating through array
while [ "$1" != "" ]
do
    case $1 in
        -f | --force) FORCE_INSTALL=true;;
        -g | --global) INSTALL_DIRECTORY="/opt/miniconda3";;
        -h | --help) echo "$__docstring"; exit 0;;
        -q | --quiet) QUIET_MODE=true;;
        -s | --silent) exec &>/dev/null;;
        -d | --install-dir) shift; INSTALL_DIRECTORY="$1/miniconda3";;
        -p | --python-version) shift; PYTHON_VERSION="$1";;
        -B | --hide-base) HIDE_BASE=true;;
        --no-auto-activate) DISABLE_AUTO_ACTIVATE=true;;
        --no-init) RUN_CONDA_INIT=false;;
        *) echo "Unexpected argument $1"; exit 1;;
    esac
    shift
done

## MAIN PROGRAM ##
echo "$__namestring"

if command -v conda &> /dev/null
then
    echo "conda is already installed at $(which conda)."
    echo "If you want to install conda using this script, you need to remove any existing conda installation."
    exit 2
fi

## Set config ##
function set_flag() {
    while true
    do
        read -rp "$1" input
        case $input in
            y) eval "$2"=true; return 0;;
            n) eval "$2"=false; return 0;;
            '') return 0;; # Use default value
            *) echo "Please enter y or n.";;
        esac
    done
}

function set_arg() {
  read -rp "$1" input
  case $input in
      '') ;; # Use default value
      *) eval "$2"="$input"
  esac
}

if ! $QUIET_MODE
then
    echo "# Configuration: (press enter to select default)"
    set_arg "Enter directory to install conda to (default: ~/.miniconda3): " "INSTALL_DIRECTORY"
    set_flag "If an existing conda installation is found at $INSTALL_DIRECTORY, overwrite? [y/n] (default: n) " "FORCE_INSTALL"
    set_arg "Enter Python version to install (default: specified by miniconda): " "PYTHON_VERSION"
    set_flag "Hide '(base)' in shell prompt? [y/n] (default: n): " "HIDE_BASE"
    set_flag "Disable automatic activation of base environment? [y/n] (default: n): " "DISABLE_AUTO_ACTIVATE"
    set_flag "Run 'conda init' after installation? [y/n] (default: y): " "RUN_CONDA_INIT"
fi

echo
echo "Selected configuration:"
echo "  INSTALL_DIRECTORY=$INSTALL_DIRECTORY"
echo "  FORCE_INSTALL=$FORCE_INSTALL"
echo "  PYTHON_VERSION=${PYTHON_VERSION:-default}"
echo "  HIDE_BASE=$HIDE_BASE"
echo "  DISABLE_AUTO_ACTIVATE=$DISABLE_AUTO_ACTIVATE"
echo "  RUN_CONDA_INIT=$RUN_CONDA_INIT"
echo

if ! $QUIET_MODE
then
  read -rp "Press enter to continue, or Ctrl-C to cancel" input
fi

## Check config is valid ##
# Check whether the specified INSTALL_DIRECTORY exists
if [ -d "$INSTALL_DIRECTORY" ] && ! $FORCE_INSTALL
then
    echo "Error installing to $INSTALL_DIRECTORY: directory already exists."
    exit 3
fi
# Check whether we have permission to create the specified INSTALL_DIRECTORY
if [ ! -w "$(dirname "$INSTALL_DIRECTORY")" ]
then
    echo "Error installing to $INSTALL_DIRECTORY: permission denied."
    exit 2
fi
# Check if the Python version is valid (up to three numbers separated by .)
if [ -n "$PYTHON_VERSION" ]
then
  PYTHON_VERSION_REGEX='^[0-9]+(\.[0-9]+){,2}$'
  if [[ ! "$PYTHON_VERSION" =~ $PYTHON_VERSION_REGEX ]]
  then
     echo "Unrecognised Python version format $PYTHON_VERSION"
     exit 5
  fi
fi

## Optionally remove existing conda installation at $INSTALL_DIRECTORY ##
if $FORCE_INSTALL
then
    echo "Overwriting conda install found at $INSTALL_DIRECTORY..."
    rm -rf "$INSTALL_DIRECTORY"
fi

## Download and install ##
echo "Downloading miniconda..."
if [ -f /tmp/miniconda-installer.sh ]
then
    echo "Miniconda already downloaded at /tmp/miniconda-installer.sh, using cached version"
else
    curl -L -# $MINICONDA_URL -o /tmp/miniconda-installer.sh
fi

echo "Installing miniconda to $INSTALL_DIRECTORY..."
bash /tmp/miniconda-installer.sh -b -p "$INSTALL_DIRECTORY"

# Save conda to PATH for the duration of this script
export PATH=$PATH:$INSTALL_DIRECTORY/bin

# Update conda
echo "Updating conda..."
conda update -y conda

# Install Python
echo "Installing Python..."
if [ -n "$PYTHON_VERSION" ]
then
  conda install -y python="$PYTHON_VERSION"
else
  conda install -y python
fi

## Optionally run 'conda init' as the active user ##
if $RUN_CONDA_INIT
then
    echo "Running 'conda init'..."
    if [ -z "$SUDO_USER" ]
    then
        conda init
    else
        sudo -u "$SUDO_USER" sh -c "$INSTALL_DIRECTORY/bin/conda init"
    fi
else
    echo "Skipping 'conda init'..."
fi

## Optionally disable auto activation of the base environment ##
if $DISABLE_AUTO_ACTIVATE
then
    echo "Disabling auto_activate_base..."
    echo "auto_activate_base: false" >> "$INSTALL_DIRECTORY"/.condarc
fi

## Optionally disable the '(base) ' prefix to PS1 prompt ##
if $HIDE_BASE
then
    echo "Hiding '(base)' in shell prompt..."
    mkdir -p "$INSTALL_DIRECTORY"/etc/conda/activate.d
    echo 'PS1="$(echo "$PS1" | sed '\''s/(base) //'\'')"' > "$INSTALL_DIRECTORY"/etc/conda/activate.d/hide_base_ps1.sh
fi

## Exit ##
echo
echo "Successfully installed conda to $INSTALL_DIRECTORY"
echo "You'll need to restart the shell to be able to activate environments"
echo
echo "Create your first environment with 'conda create -n myenv'"
echo "Activate an environment with 'conda activate myenv'"
echo "Install a package with 'conda install <package_name>'"
echo "Deactivate the active environment with 'conda deactivate'"
